const mongoose = require('mongoose');

const MONGO_URI = 'mongodb+srv://coder:CVy0ppVfzCu1rGaK@coder.zwswr0y.mongodb.net/codingapp';

const topicDefs = [
  { name: 'Arrays',               order: 1,  difficulty: 'Beginner',     description: 'Array traversal, manipulation and sliding window.' },
  { name: 'Strings',              order: 2,  difficulty: 'Beginner',     description: 'String manipulation and pattern matching.' },
  { name: 'Loops & Conditionals', order: 3,  difficulty: 'Beginner',     description: 'Control flow, nested loops and iteration patterns.' },
  { name: 'Mathematics',          order: 4,  difficulty: 'Beginner',     description: 'GCD, LCM, primes, modular arithmetic.' },
  { name: 'Searching & Sorting',  order: 5,  difficulty: 'Intermediate', description: 'Binary search, merge sort, quick sort.' },
  { name: 'Recursion',            order: 6,  difficulty: 'Intermediate', description: 'Divide and conquer, backtracking.' },
  { name: 'Linked Lists',         order: 7,  difficulty: 'Intermediate', description: 'Linked list manipulation and pointer patterns.' },
  { name: 'Stacks & Queues',      order: 8,  difficulty: 'Intermediate', description: 'LIFO, FIFO structures, monotonic stacks.' },
  { name: 'Hashing',              order: 9,  difficulty: 'Intermediate', description: 'Hash maps, frequency counting and grouping.' },
  { name: 'Trees',                order: 10, difficulty: 'Intermediate', description: 'Binary trees, BST, DFS and BFS traversal.' },
  { name: 'Dynamic Programming',  order: 11, difficulty: 'Advanced',     description: 'Memoization, tabulation, knapsack patterns.' },
  { name: 'Graphs',               order: 12, difficulty: 'Advanced',     description: 'BFS, DFS, shortest path algorithms.' },
];

// Questions per topic (index 0-11 maps to topicDefs order)
function buildQuestions(tids) {
  return [
    // ── Arrays ──
    { title: 'Two Sum', difficulty: 'Easy', topic: tids[0], companies: ['Google','Amazon','Microsoft','Facebook'], tags: ['array','hash-table'],
      description: 'Given an array of integers and a target, return indices of two numbers that add up to target.',
      inputFormat: 'First line: n\nSecond line: n integers\nThird line: target', outputFormat: 'Two space-separated indices',
      constraints: '2 <= n <= 10^4',
      sampleTestCases: [{input:'4\n2 7 11 15\n9',output:'0 1',explanation:'arr[0]+arr[1]=9'},{input:'3\n3 2 4\n6',output:'1 2',explanation:'arr[1]+arr[2]=6'}],
      hiddenTestCases: [{input:'2\n1 2\n3',output:'0 1'},{input:'4\n0 4 3 0\n0',output:'0 3'}],
      hints: ['Use a hash map to store seen values','For each element check if target-element exists in map'],
      starterCode: { python: 'n = int(input())\narr = list(map(int, input().split()))\ntarget = int(input())\n# Your code here', cpp: '#include <iostream>\nusing namespace std;\nint main() {\n    int n; cin >> n;\n    int arr[n], target;\n    for(int i=0;i<n;i++) cin>>arr[i];\n    cin >> target;\n    // Your code here\n    return 0;\n}', c: '#include <stdio.h>\nint main() {\n    int n; scanf("%d",&n);\n    int arr[n], target;\n    for(int i=0;i<n;i++) scanf("%d",&arr[i]);\n    scanf("%d",&target);\n    // Your code here\n    return 0;\n}' } },
    { title: 'Maximum Subarray', difficulty: 'Medium', topic: tids[0], companies: ['Amazon','Apple','Google'], tags: ['array','dynamic-programming'],
      description: 'Given an integer array, find the contiguous subarray with the largest sum and return its sum.',
      inputFormat: 'First line: n\nSecond line: n integers', outputFormat: 'Maximum subarray sum',
      constraints: '1 <= n <= 10^5',
      sampleTestCases: [{input:'9\n-2 1 -3 4 -1 2 1 -5 4',output:'6',explanation:'[4,-1,2,1] has sum 6'},{input:'1\n1',output:'1'}],
      hiddenTestCases: [{input:'4\n-1 -2 -3 -4',output:'-1'},{input:'5\n5 4 -1 7 8',output:'23'}],
      hints: ['Kadane\'s algorithm: track current and overall max','If current sum becomes negative, reset to 0'],
      starterCode: { python: 'n = int(input())\narr = list(map(int, input().split()))\n# Your code here', cpp: '#include <iostream>\nusing namespace std;\nint main() {\n    int n; cin>>n;\n    int arr[n];\n    for(int i=0;i<n;i++) cin>>arr[i];\n    // Your code here\n    return 0;\n}', c: '#include <stdio.h>\nint main() {\n    int n; scanf("%d",&n);\n    int arr[n];\n    for(int i=0;i<n;i++) scanf("%d",&arr[i]);\n    // Your code here\n    return 0;\n}' } },
    { title: 'Best Time to Buy and Sell Stock', difficulty: 'Easy', topic: tids[0], companies: ['Amazon','Facebook','Google'], tags: ['array','greedy'],
      description: 'Given prices of a stock on different days, find the maximum profit you can achieve from one buy and one sell.',
      inputFormat: 'First line: n\nSecond line: n prices', outputFormat: 'Maximum profit',
      constraints: '1 <= n <= 10^5',
      sampleTestCases: [{input:'6\n7 1 5 3 6 4',output:'5',explanation:'Buy at 1, sell at 6'},{input:'5\n7 6 4 3 1',output:'0',explanation:'No profit possible'}],
      hiddenTestCases: [{input:'4\n2 4 1 7',output:'6'},{input:'2\n1 2',output:'1'}],
      hints: ['Track minimum price seen so far','Calculate max profit at each step'],
      starterCode: { python: 'n = int(input())\nprices = list(map(int, input().split()))\n# Your code here', cpp: '#include <iostream>\nusing namespace std;\nint main() {\n    int n; cin>>n;\n    int p[n];\n    for(int i=0;i<n;i++) cin>>p[i];\n    // Your code here\n    return 0;\n}', c: '#include <stdio.h>\nint main() {\n    int n; scanf("%d",&n);\n    int p[n];\n    for(int i=0;i<n;i++) scanf("%d",&p[i]);\n    // Your code here\n    return 0;\n}' } },

    // ── Strings ──
    { title: 'Valid Parentheses', difficulty: 'Easy', topic: tids[1], companies: ['Google','Amazon','Microsoft'], tags: ['string','stack'],
      description: 'Given a string containing only (, ), {, }, [ and ], determine if the input string is valid.',
      inputFormat: 'A single string', outputFormat: 'true or false',
      constraints: '1 <= s.length <= 10^4',
      sampleTestCases: [{input:'()',output:'true'},{input:'()[]{}}',output:'false'}],
      hiddenTestCases: [{input:'{[]}',output:'true'},{input:'([)]',output:'false'}],
      hints: ['Use a stack','Push open brackets, pop and match on close brackets'],
      starterCode: { python: 's = input()\n# Your code here', cpp: '#include <iostream>\nusing namespace std;\nint main() {\n    string s; cin>>s;\n    // Your code here\n    return 0;\n}', c: '#include <stdio.h>\n#include <string.h>\nint main() {\n    char s[10001]; scanf("%s",s);\n    // Your code here\n    return 0;\n}' } },
    { title: 'Longest Palindromic Substring', difficulty: 'Medium', topic: tids[1], companies: ['Amazon','Microsoft','Apple'], tags: ['string','dynamic-programming'],
      description: 'Given a string s, return the longest palindromic substring in s.',
      inputFormat: 'A single string', outputFormat: 'The longest palindromic substring',
      constraints: '1 <= s.length <= 1000',
      sampleTestCases: [{input:'babad',output:'bab'},{input:'cbbd',output:'bb'}],
      hiddenTestCases: [{input:'a',output:'a'},{input:'racecar',output:'racecar'}],
      hints: ['Expand around each center','Consider both odd and even length palindromes'],
      starterCode: { python: 's = input()\n# Your code here', cpp: '#include <iostream>\nusing namespace std;\nint main() {\n    string s; cin>>s;\n    // Your code here\n    return 0;\n}', c: '#include <stdio.h>\n#include <string.h>\nint main() {\n    char s[1001]; scanf("%s",s);\n    // Your code here\n    return 0;\n}' } },
    { title: 'Reverse Words in a String', difficulty: 'Medium', topic: tids[1], companies: ['Microsoft','Apple','Amazon'], tags: ['string','two-pointer'],
      description: 'Given a string s, reverse the order of words.',
      inputFormat: 'A single string', outputFormat: 'String with words reversed',
      constraints: '1 <= s.length <= 10^4',
      sampleTestCases: [{input:'the sky is blue',output:'blue is sky the'},{input:'  hello world  ',output:'world hello'}],
      hiddenTestCases: [{input:'a good   example',output:'example good a'},{input:'hi',output:'hi'}],
      hints: ['Split by spaces, filter empty, reverse the list'],
      starterCode: { python: 's = input()\n# Your code here', cpp: '#include <iostream>\n#include <sstream>\nusing namespace std;\nint main() {\n    string s; getline(cin,s);\n    // Your code here\n    return 0;\n}', c: '#include <stdio.h>\n#include <string.h>\nint main() {\n    char s[10001]; fgets(s,sizeof(s),stdin);\n    // Your code here\n    return 0;\n}' } },

    // ── Loops & Conditionals ──
    { title: 'FizzBuzz', difficulty: 'Easy', topic: tids[2], companies: ['Google','Microsoft','Amazon'], tags: ['loops','math'],
      description: 'Print numbers from 1 to n. For multiples of 3 print Fizz, multiples of 5 print Buzz, both print FizzBuzz.',
      inputFormat: 'A single integer n', outputFormat: 'n lines',
      constraints: '1 <= n <= 10^4',
      sampleTestCases: [{input:'15',output:'1\n2\nFizz\n4\nBuzz\nFizz\n7\n8\nFizz\nBuzz\n11\nFizz\n13\n14\nFizzBuzz',explanation:'Classic FizzBuzz'}],
      hiddenTestCases: [{input:'3',output:'1\n2\nFizz'},{input:'5',output:'1\n2\nFizz\n4\nBuzz'}],
      hints: ['Check divisible by 15 first, then 3, then 5'],
      starterCode: { python: 'n = int(input())\n# Your code here', cpp: '#include <iostream>\nusing namespace std;\nint main() {\n    int n; cin>>n;\n    // Your code here\n    return 0;\n}', c: '#include <stdio.h>\nint main() {\n    int n; scanf("%d",&n);\n    // Your code here\n    return 0;\n}' } },
    { title: 'Print Number Pattern', difficulty: 'Easy', topic: tids[2], companies: ['Infosys','TCS'], tags: ['loops','pattern'],
      description: 'Given n, print a right triangle pattern where row i has numbers 1 to i.',
      inputFormat: 'A single integer n', outputFormat: 'n rows of numbers',
      constraints: '1 <= n <= 20',
      sampleTestCases: [{input:'4',output:'1\n1 2\n1 2 3\n1 2 3 4'}],
      hiddenTestCases: [{input:'1',output:'1'},{input:'3',output:'1\n1 2\n1 2 3'}],
      hints: ['Outer loop for rows, inner loop from 1 to row number'],
      starterCode: { python: 'n = int(input())\n# Your code here', cpp: '#include <iostream>\nusing namespace std;\nint main() {\n    int n; cin>>n;\n    // Your code here\n    return 0;\n}', c: '#include <stdio.h>\nint main() {\n    int n; scanf("%d",&n);\n    // Your code here\n    return 0;\n}' } },

    // ── Mathematics ──
    { title: 'Count Primes', difficulty: 'Medium', topic: tids[3], companies: ['Amazon','Microsoft','Apple'], tags: ['math','sieve'],
      description: 'Given an integer n, return the number of prime numbers strictly less than n.',
      inputFormat: 'A single integer n', outputFormat: 'Count of primes less than n',
      constraints: '0 <= n <= 5 * 10^6',
      sampleTestCases: [{input:'10',output:'4',explanation:'2,3,5,7'},{input:'0',output:'0'}],
      hiddenTestCases: [{input:'1',output:'0'},{input:'100',output:'25'}],
      hints: ['Use Sieve of Eratosthenes','Mark multiples of each prime as composite'],
      starterCode: { python: 'n = int(input())\n# Your code here', cpp: '#include <iostream>\nusing namespace std;\nint main() {\n    int n; cin>>n;\n    // Your code here\n    return 0;\n}', c: '#include <stdio.h>\nint main() {\n    int n; scanf("%d",&n);\n    // Your code here\n    return 0;\n}' } },
    { title: 'GCD of Two Numbers', difficulty: 'Easy', topic: tids[3], companies: ['Google','Adobe'], tags: ['math','recursion'],
      description: 'Given two integers a and b, return their greatest common divisor.',
      inputFormat: 'Two integers a and b', outputFormat: 'GCD',
      constraints: '1 <= a, b <= 10^9',
      sampleTestCases: [{input:'12 8',output:'4'},{input:'7 14',output:'7'}],
      hiddenTestCases: [{input:'1 1',output:'1'},{input:'100 75',output:'25'}],
      hints: ['Use Euclidean algorithm: gcd(a,b) = gcd(b, a%b)'],
      starterCode: { python: 'a, b = map(int, input().split())\n# Your code here', cpp: '#include <iostream>\nusing namespace std;\nint main() {\n    int a, b; cin>>a>>b;\n    // Your code here\n    return 0;\n}', c: '#include <stdio.h>\nint main() {\n    int a,b; scanf("%d %d",&a,&b);\n    // Your code here\n    return 0;\n}' } },
    { title: 'Power of Two', difficulty: 'Easy', topic: tids[3], companies: ['Google','Amazon'], tags: ['math','bit-manipulation'],
      description: 'Given an integer n, return true if it is a power of two.',
      inputFormat: 'A single integer n', outputFormat: 'true or false',
      constraints: '-2^31 <= n <= 2^31 - 1',
      sampleTestCases: [{input:'1',output:'true'},{input:'3',output:'false'},{input:'16',output:'true'}],
      hiddenTestCases: [{input:'0',output:'false'},{input:'1024',output:'true'}],
      hints: ['n > 0 and (n & (n-1)) == 0 for powers of 2'],
      starterCode: { python: 'n = int(input())\n# Your code here', cpp: '#include <iostream>\nusing namespace std;\nint main() {\n    int n; cin>>n;\n    // Your code here\n    return 0;\n}', c: '#include <stdio.h>\nint main() {\n    int n; scanf("%d",&n);\n    // Your code here\n    return 0;\n}' } },

    // ── Searching & Sorting ──
    { title: 'Binary Search', difficulty: 'Easy', topic: tids[4], companies: ['Google','Amazon','Facebook'], tags: ['binary-search','array'],
      description: 'Given a sorted array and target, return the index of target or -1 if not found.',
      inputFormat: 'First line: n\nSecond line: n sorted integers\nThird line: target', outputFormat: 'Index or -1',
      constraints: '1 <= n <= 10^4',
      sampleTestCases: [{input:'6\n-1 0 3 5 9 12\n9',output:'4'},{input:'6\n-1 0 3 5 9 12\n2',output:'-1'}],
      hiddenTestCases: [{input:'1\n5\n5',output:'0'},{input:'3\n1 3 5\n3',output:'1'}],
      hints: ['Use left and right pointers','mid = left + (right-left)/2'],
      starterCode: { python: 'n = int(input())\narr = list(map(int, input().split()))\ntarget = int(input())\n# Your code here', cpp: '#include <iostream>\nusing namespace std;\nint main() {\n    int n; cin>>n;\n    int arr[n], target;\n    for(int i=0;i<n;i++) cin>>arr[i];\n    cin>>target;\n    // Your code here\n    return 0;\n}', c: '#include <stdio.h>\nint main() {\n    int n; scanf("%d",&n);\n    int arr[n], target;\n    for(int i=0;i<n;i++) scanf("%d",&arr[i]);\n    scanf("%d",&target);\n    // Your code here\n    return 0;\n}' } },
    { title: 'Sort Colors', difficulty: 'Medium', topic: tids[4], companies: ['Facebook','Microsoft','Amazon'], tags: ['array','sorting','two-pointer'],
      description: 'Given array with 0s, 1s, 2s (Dutch national flag), sort in-place without using library sort.',
      inputFormat: 'First line: n\nSecond line: n integers (0,1,2)', outputFormat: 'Space-separated sorted array',
      constraints: '1 <= n <= 300',
      sampleTestCases: [{input:'6\n2 0 2 1 1 0',output:'0 0 1 1 2 2'},{input:'3\n2 0 1',output:'0 1 2'}],
      hiddenTestCases: [{input:'1\n0',output:'0'},{input:'4\n1 0 1 0',output:'0 0 1 1'}],
      hints: ['Dutch national flag algorithm: 3 pointers low, mid, high'],
      starterCode: { python: 'n = int(input())\narr = list(map(int, input().split()))\n# Your code here\nprint(*arr)', cpp: '#include <iostream>\nusing namespace std;\nint main() {\n    int n; cin>>n;\n    int arr[n];\n    for(int i=0;i<n;i++) cin>>arr[i];\n    // Your code here\n    return 0;\n}', c: '#include <stdio.h>\nint main() {\n    int n; scanf("%d",&n);\n    int arr[n];\n    for(int i=0;i<n;i++) scanf("%d",&arr[i]);\n    // Your code here\n    return 0;\n}' } },
    { title: 'Merge Intervals', difficulty: 'Medium', topic: tids[4], companies: ['Google','Facebook','Microsoft'], tags: ['array','sorting'],
      description: 'Given an array of intervals, merge all overlapping intervals.',
      inputFormat: 'First line: n\nNext n lines: start end', outputFormat: 'Merged intervals, one per line',
      constraints: '1 <= n <= 10^4',
      sampleTestCases: [{input:'4\n1 3\n2 6\n8 10\n15 18',output:'1 6\n8 10\n15 18'},{input:'2\n1 4\n4 5',output:'1 5'}],
      hiddenTestCases: [{input:'1\n1 1',output:'1 1'},{input:'3\n1 4\n0 2\n3 5',output:'0 5'}],
      hints: ['Sort by start time','If current start <= prev end, merge'],
      starterCode: { python: 'n = int(input())\nintervals = [list(map(int,input().split())) for _ in range(n)]\n# Your code here', cpp: '#include <iostream>\n#include <vector>\n#include <algorithm>\nusing namespace std;\nint main() {\n    int n; cin>>n;\n    vector<pair<int,int>> v(n);\n    for(auto& p:v) cin>>p.first>>p.second;\n    // Your code here\n    return 0;\n}', c: '#include <stdio.h>\nint main() {\n    // Your code here\n    return 0;\n}' } },

    // ── Recursion ──
    { title: 'Fibonacci Number', difficulty: 'Easy', topic: tids[5], companies: ['Google','Amazon','Microsoft'], tags: ['recursion','dynamic-programming'],
      description: 'Given n, compute the nth Fibonacci number. F(0)=0, F(1)=1, F(n)=F(n-1)+F(n-2).',
      inputFormat: 'A single integer n', outputFormat: 'nth Fibonacci number',
      constraints: '0 <= n <= 30',
      sampleTestCases: [{input:'4',output:'3'},{input:'6',output:'8'}],
      hiddenTestCases: [{input:'0',output:'0'},{input:'1',output:'1'},{input:'10',output:'55'}],
      hints: ['Use memoization to avoid recomputation','Or use bottom-up DP'],
      starterCode: { python: 'n = int(input())\n# Your code here', cpp: '#include <iostream>\nusing namespace std;\nint main() {\n    int n; cin>>n;\n    // Your code here\n    return 0;\n}', c: '#include <stdio.h>\nint main() {\n    int n; scanf("%d",&n);\n    // Your code here\n    return 0;\n}' } },
    { title: 'Subsets', difficulty: 'Medium', topic: tids[5], companies: ['Facebook','Amazon','Google'], tags: ['recursion','backtracking'],
      description: 'Given an integer array of unique elements, return all possible subsets (power set).',
      inputFormat: 'First line: n\nSecond line: n distinct integers', outputFormat: 'Each subset on a new line, sorted',
      constraints: '1 <= n <= 10',
      sampleTestCases: [{input:'3\n1 2 3',output:'\n1\n1 2\n1 2 3\n1 3\n2\n2 3\n3'}],
      hiddenTestCases: [{input:'1\n1',output:'\n1'}],
      hints: ['For each element, choose to include or exclude','Use backtracking'],
      starterCode: { python: 'n = int(input())\narr = list(map(int, input().split()))\n# Your code here', cpp: '#include <iostream>\n#include <vector>\nusing namespace std;\nint main() {\n    int n; cin>>n;\n    vector<int> arr(n);\n    for(int& x:arr) cin>>x;\n    // Your code here\n    return 0;\n}', c: '#include <stdio.h>\nint main() {\n    // Your code here\n    return 0;\n}' } },
    { title: 'Tower of Hanoi', difficulty: 'Medium', topic: tids[5], companies: ['Google','Adobe'], tags: ['recursion'],
      description: 'Move n disks from rod A to rod C using rod B as auxiliary. Print each move.',
      inputFormat: 'A single integer n', outputFormat: 'Each move on a new line: "Move disk X from Y to Z"',
      constraints: '1 <= n <= 10',
      sampleTestCases: [{input:'2',output:'Move disk 1 from A to B\nMove disk 2 from A to C\nMove disk 1 from B to C'}],
      hiddenTestCases: [{input:'1',output:'Move disk 1 from A to C'}],
      hints: ['Recursively move n-1 disks, move largest, move n-1 disks again'],
      starterCode: { python: 'n = int(input())\n# Your code here', cpp: '#include <iostream>\nusing namespace std;\nint main() {\n    int n; cin>>n;\n    // Your code here\n    return 0;\n}', c: '#include <stdio.h>\nint main() {\n    int n; scanf("%d",&n);\n    // Your code here\n    return 0;\n}' } },

    // ── Linked Lists ──
    { title: 'Reverse Linked List', difficulty: 'Easy', topic: tids[6], companies: ['Amazon','Microsoft','Facebook'], tags: ['linked-list'],
      description: 'Given a singly linked list, reverse it and return the head of reversed list.',
      inputFormat: 'First line: n\nSecond line: n integers (node values)', outputFormat: 'Reversed list values space-separated',
      constraints: '0 <= n <= 5000',
      sampleTestCases: [{input:'5\n1 2 3 4 5',output:'5 4 3 2 1'},{input:'2\n1 2',output:'2 1'}],
      hiddenTestCases: [{input:'0\n',output:''},{input:'1\n1',output:'1'}],
      hints: ['Use 3 pointers: prev, curr, next','Iteratively reverse links'],
      starterCode: { python: 'n = int(input())\narr = list(map(int, input().split())) if n > 0 else []\n# Your code here (simulate with array)', cpp: '#include <iostream>\nusing namespace std;\nint main() {\n    int n; cin>>n;\n    // Your code here\n    return 0;\n}', c: '#include <stdio.h>\nint main() {\n    // Your code here\n    return 0;\n}' } },
    { title: 'Middle of Linked List', difficulty: 'Easy', topic: tids[6], companies: ['Amazon','Facebook'], tags: ['linked-list','two-pointer'],
      description: 'Find the middle node of a linked list. If two middles, return the second.',
      inputFormat: 'First line: n\nSecond line: n integers', outputFormat: 'Values from middle to end',
      constraints: '1 <= n <= 100',
      sampleTestCases: [{input:'5\n1 2 3 4 5',output:'3 4 5'},{input:'6\n1 2 3 4 5 6',output:'4 5 6'}],
      hiddenTestCases: [{input:'1\n1',output:'1'},{input:'3\n1 2 3',output:'2 3'}],
      hints: ['Use fast and slow pointer','Fast moves 2 steps, slow moves 1'],
      starterCode: { python: 'n = int(input())\narr = list(map(int, input().split()))\n# Your code here', cpp: '#include <iostream>\nusing namespace std;\nint main() {\n    int n; cin>>n;\n    // Your code here\n    return 0;\n}', c: '#include <stdio.h>\nint main() {\n    // Your code here\n    return 0;\n}' } },

    // ── Stacks & Queues ──
    { title: 'Implement Stack using Queues', difficulty: 'Easy', topic: tids[7], companies: ['Amazon','Microsoft'], tags: ['stack','queue','design'],
      description: 'Implement a LIFO stack using only Queue operations.',
      inputFormat: 'Queries: push x, pop, top, empty', outputFormat: 'Output for pop, top, empty',
      constraints: '1 <= x <= 9',
      sampleTestCases: [{input:'push 1\npush 2\ntop\npop\nempty',output:'2\n2\nfalse'}],
      hiddenTestCases: [{input:'push 5\npop\nempty',output:'5\ntrue'}],
      hints: ['After each push, rotate queue so new element is at front'],
      starterCode: { python: '# Simulate with list\nstack = []\nimport sys\nfor line in sys.stdin:\n    line = line.strip()\n    if not line: break\n    # Your code here', cpp: '#include <iostream>\n#include <queue>\nusing namespace std;\nint main() {\n    // Your code here\n    return 0;\n}', c: '#include <stdio.h>\nint main() {\n    // Your code here\n    return 0;\n}' } },
    { title: 'Next Greater Element', difficulty: 'Medium', topic: tids[7], companies: ['Amazon','Google','Microsoft'], tags: ['stack','array','monotonic-stack'],
      description: 'For each element in array, find the next greater element to its right. Output -1 if none.',
      inputFormat: 'First line: n\nSecond line: n integers', outputFormat: 'n space-separated values',
      constraints: '1 <= n <= 10^4',
      sampleTestCases: [{input:'4\n4 5 2 25',output:'-1 25 25 -1',explanation:'For 4->5, 5->25, 2->25, 25->-1'},{input:'5\n13 7 6 12 1',output:'-1 12 12 -1 -1'}],
      hiddenTestCases: [{input:'1\n1',output:'-1'},{input:'3\n1 2 3',output:'2 3 -1'}],
      hints: ['Use a monotonic decreasing stack','Pop stack when current element is greater'],
      starterCode: { python: 'n = int(input())\narr = list(map(int, input().split()))\n# Your code here', cpp: '#include <iostream>\n#include <stack>\nusing namespace std;\nint main() {\n    int n; cin>>n;\n    int arr[n];\n    for(int i=0;i<n;i++) cin>>arr[i];\n    // Your code here\n    return 0;\n}', c: '#include <stdio.h>\nint main() {\n    // Your code here\n    return 0;\n}' } },
    { title: 'Sliding Window Maximum', difficulty: 'Hard', topic: tids[7], companies: ['Google','Amazon','Uber'], tags: ['sliding-window','deque','monotonic-stack'],
      description: 'Given array and window size k, find the maximum in each sliding window.',
      inputFormat: 'First line: n and k\nSecond line: n integers', outputFormat: 'Maximums for each window',
      constraints: '1 <= k <= n <= 10^5',
      sampleTestCases: [{input:'8 3\n1 3 -1 -3 5 3 6 7',output:'3 3 5 5 6 7'},{input:'4 1\n1 -1',output:'1 -1'}],
      hiddenTestCases: [{input:'3 3\n1 3 1',output:'3'},{input:'1 1\n7',output:'7'}],
      hints: ['Use monotonic deque storing indices','Pop from front if out of window, from back if smaller'],
      starterCode: { python: 'data = list(map(int, input().split()))\nn, k = data[0], data[1]\narr = list(map(int, input().split()))\n# Your code here', cpp: '#include <iostream>\n#include <deque>\nusing namespace std;\nint main() {\n    int n,k; cin>>n>>k;\n    int arr[n];\n    for(int i=0;i<n;i++) cin>>arr[i];\n    // Your code here\n    return 0;\n}', c: '#include <stdio.h>\nint main() {\n    // Your code here\n    return 0;\n}' } },

    // ── Hashing ──
    { title: 'Two Sum (HashMap)', difficulty: 'Easy', topic: tids[8], companies: ['Google','Amazon','Microsoft'], tags: ['hash-table','array'],
      description: 'Find all pairs in array that sum to target. Return count of pairs.',
      inputFormat: 'First line: n\nSecond line: n integers\nThird line: target', outputFormat: 'Count of pairs',
      constraints: '1 <= n <= 10^5',
      sampleTestCases: [{input:'4\n1 5 3 2\n6',output:'2',explanation:'(1,5) and (3,3) wait, (1,5) and (2,4) -- (1,5) valid pair'},{input:'3\n1 2 3\n4',output:'1'}],
      hiddenTestCases: [{input:'2\n1 1\n2',output:'1'},{input:'4\n0 1 2 3\n5',output:'1'}],
      hints: ['Use a frequency map','For each element check if complement exists'],
      starterCode: { python: 'n = int(input())\narr = list(map(int, input().split()))\ntarget = int(input())\n# Your code here', cpp: '#include <iostream>\n#include <unordered_map>\nusing namespace std;\nint main() {\n    int n; cin>>n;\n    int arr[n], target;\n    for(int i=0;i<n;i++) cin>>arr[i];\n    cin>>target;\n    // Your code here\n    return 0;\n}', c: '#include <stdio.h>\nint main() {\n    // Your code here\n    return 0;\n}' } },
    { title: 'Group Anagrams', difficulty: 'Medium', topic: tids[8], companies: ['Facebook','Amazon','Google'], tags: ['hash-table','string','sorting'],
      description: 'Given an array of strings, group anagrams together.',
      inputFormat: 'First line: n\nNext n lines: one string each', outputFormat: 'Groups separated by newline, sorted within group',
      constraints: '1 <= n <= 10^4',
      sampleTestCases: [{input:'6\neat\ntea\ntan\nate\nnat\nbat',output:'ate eat tea\nnat tan\nbat'}],
      hiddenTestCases: [{input:'1\na',output:'a'},{input:'2\nab\nba',output:'ab ba'}],
      hints: ['Sort each string to use as key','Group by sorted string key'],
      starterCode: { python: 'n = int(input())\nwords = [input() for _ in range(n)]\n# Your code here', cpp: '#include <iostream>\n#include <vector>\n#include <unordered_map>\n#include <algorithm>\nusing namespace std;\nint main() {\n    int n; cin>>n;\n    vector<string> words(n);\n    for(auto& w:words) cin>>w;\n    // Your code here\n    return 0;\n}', c: '#include <stdio.h>\nint main() {\n    // Your code here\n    return 0;\n}' } },

    // ── Trees ──
    { title: 'Maximum Depth of Binary Tree', difficulty: 'Easy', topic: tids[9], companies: ['Amazon','Google','Facebook'], tags: ['tree','dfs','recursion'],
      description: 'Given the root of a binary tree, return its maximum depth.',
      inputFormat: 'Level-order input, -1 for null. First line: n nodes', outputFormat: 'Maximum depth',
      constraints: '0 <= n <= 10^4',
      sampleTestCases: [{input:'3\n3 9 20',output:'2'},{input:'5\n3 9 20 -1 -1 15 7',output:'3'}],
      hiddenTestCases: [{input:'0\n',output:'0'},{input:'1\n1',output:'1'}],
      hints: ['Recursively find max depth of left and right subtree','Return 1 + max(left, right)'],
      starterCode: { python: '# Tree given as level-order list\nfrom collections import deque\nvals = list(map(int, input().split())) if input().strip() else []\n# Build tree and find depth', cpp: '#include <iostream>\nusing namespace std;\nint main() {\n    // Your code here\n    return 0;\n}', c: '#include <stdio.h>\nint main() {\n    // Your code here\n    return 0;\n}' } },
    { title: 'Validate Binary Search Tree', difficulty: 'Medium', topic: tids[9], companies: ['Amazon','Microsoft','Facebook'], tags: ['tree','dfs','bst'],
      description: 'Given the root of a binary tree, determine if it is a valid binary search tree.',
      inputFormat: 'Level-order input, -1 for null', outputFormat: 'true or false',
      constraints: '1 <= n <= 10^4',
      sampleTestCases: [{input:'3\n2 1 3',output:'true'},{input:'5\n5 1 4 -1 -1 3 6',output:'false'}],
      hiddenTestCases: [{input:'1\n1',output:'true'}],
      hints: ['Pass min and max bounds during recursion','Left < node < Right'],
      starterCode: { python: '# Your code here', cpp: '#include <iostream>\n#include <climits>\nusing namespace std;\nint main() {\n    // Your code here\n    return 0;\n}', c: '#include <stdio.h>\nint main() {\n    // Your code here\n    return 0;\n}' } },
    { title: 'Level Order Traversal', difficulty: 'Medium', topic: tids[9], companies: ['Amazon','Microsoft','Google'], tags: ['tree','bfs'],
      description: 'Return the level order traversal of a binary tree (left to right, level by level).',
      inputFormat: 'Level-order input, -1 for null', outputFormat: 'Each level on a new line',
      constraints: '0 <= n <= 2000',
      sampleTestCases: [{input:'5\n3 9 20 -1 -1 15 7',output:'3\n9 20\n15 7'}],
      hiddenTestCases: [{input:'1\n1',output:'1'},{input:'0\n',output:''}],
      hints: ['Use a queue','Process level by level, track level size'],
      starterCode: { python: '# Your code here', cpp: '#include <iostream>\n#include <queue>\nusing namespace std;\nint main() {\n    // Your code here\n    return 0;\n}', c: '#include <stdio.h>\nint main() {\n    // Your code here\n    return 0;\n}' } },

    // ── Dynamic Programming ──
    { title: 'Climbing Stairs', difficulty: 'Easy', topic: tids[10], companies: ['Amazon','Microsoft','Apple'], tags: ['dynamic-programming','math'],
      description: 'You can climb 1 or 2 steps at a time. How many distinct ways to reach the top of n stairs?',
      inputFormat: 'A single integer n', outputFormat: 'Number of ways',
      constraints: '1 <= n <= 45',
      sampleTestCases: [{input:'2',output:'2',explanation:'1+1 or 2'},{input:'3',output:'3',explanation:'1+1+1, 1+2, 2+1'}],
      hiddenTestCases: [{input:'1',output:'1'},{input:'4',output:'5'},{input:'10',output:'89'}],
      hints: ['dp[i] = dp[i-1] + dp[i-2]','Same recurrence as Fibonacci'],
      starterCode: { python: 'n = int(input())\n# Your code here', cpp: '#include <iostream>\nusing namespace std;\nint main() {\n    int n; cin>>n;\n    // Your code here\n    return 0;\n}', c: '#include <stdio.h>\nint main() {\n    int n; scanf("%d",&n);\n    // Your code here\n    return 0;\n}' } },
    { title: 'Longest Increasing Subsequence', difficulty: 'Medium', topic: tids[10], companies: ['Microsoft','Google','Amazon'], tags: ['dynamic-programming','binary-search'],
      description: 'Given an integer array, return the length of the longest strictly increasing subsequence.',
      inputFormat: 'First line: n\nSecond line: n integers', outputFormat: 'LIS length',
      constraints: '1 <= n <= 2500',
      sampleTestCases: [{input:'8\n10 9 2 5 3 7 101 18',output:'4',explanation:'[2,3,7,101]'},{input:'3\n0 1 0',output:'2'}],
      hiddenTestCases: [{input:'1\n0',output:'1'},{input:'5\n1 2 3 4 5',output:'5'}],
      hints: ['dp[i] = longest IS ending at index i','For each i, check all j < i where arr[j] < arr[i]'],
      starterCode: { python: 'n = int(input())\narr = list(map(int, input().split()))\n# Your code here', cpp: '#include <iostream>\nusing namespace std;\nint main() {\n    int n; cin>>n;\n    int arr[n];\n    for(int i=0;i<n;i++) cin>>arr[i];\n    // Your code here\n    return 0;\n}', c: '#include <stdio.h>\nint main() {\n    // Your code here\n    return 0;\n}' } },
    { title: 'Coin Change', difficulty: 'Medium', topic: tids[10], companies: ['Amazon','Google','Microsoft'], tags: ['dynamic-programming','bfs'],
      description: 'Given coins and amount, find the minimum number of coins needed to make the amount. Return -1 if impossible.',
      inputFormat: 'First line: n and amount\nSecond line: n coin values', outputFormat: 'Minimum coins or -1',
      constraints: '1 <= n <= 12, 0 <= amount <= 10^4',
      sampleTestCases: [{input:'3 11\n1 5 6',output:'2',explanation:'5+6=11'},{input:'2 3\n2 4',output:'-1'}],
      hiddenTestCases: [{input:'1 0\n1',output:'0'},{input:'1 2\n1',output:'2'}],
      hints: ['dp[i] = min coins to make amount i','dp[i] = min(dp[i], dp[i-coin]+1) for each coin'],
      starterCode: { python: 'data = list(map(int, input().split()))\nn, amount = data[0], data[1]\ncoins = list(map(int, input().split()))\n# Your code here', cpp: '#include <iostream>\n#include <vector>\n#include <climits>\nusing namespace std;\nint main() {\n    int n, amount; cin>>n>>amount;\n    vector<int> coins(n);\n    for(int& c:coins) cin>>c;\n    // Your code here\n    return 0;\n}', c: '#include <stdio.h>\nint main() {\n    // Your code here\n    return 0;\n}' } },

    // ── Graphs ──
    { title: 'Number of Islands', difficulty: 'Medium', topic: tids[11], companies: ['Amazon','Facebook','Google'], tags: ['graph','dfs','bfs'],
      description: 'Given a 2D grid of 1s (land) and 0s (water), count the number of islands.',
      inputFormat: 'First line: rows cols\nNext rows lines: grid row', outputFormat: 'Number of islands',
      constraints: '1 <= rows, cols <= 300',
      sampleTestCases: [{input:'4 5\n1 1 1 1 0\n1 1 0 1 0\n1 1 0 0 0\n0 0 0 0 0',output:'1'},{input:'4 5\n1 1 0 0 0\n1 1 0 0 0\n0 0 1 0 0\n0 0 0 1 1',output:'3'}],
      hiddenTestCases: [{input:'1 1\n1',output:'1'},{input:'1 1\n0',output:'0'}],
      hints: ['DFS/BFS from each unvisited land cell','Mark visited cells to avoid counting twice'],
      starterCode: { python: 'r, c = map(int, input().split())\ngrid = [list(map(int, input().split())) for _ in range(r)]\n# Your code here', cpp: '#include <iostream>\nusing namespace std;\nint main() {\n    int r,c; cin>>r>>c;\n    int grid[r][c];\n    for(int i=0;i<r;i++) for(int j=0;j<c;j++) cin>>grid[i][j];\n    // Your code here\n    return 0;\n}', c: '#include <stdio.h>\nint main() {\n    // Your code here\n    return 0;\n}' } },
    { title: 'Course Schedule', difficulty: 'Medium', topic: tids[11], companies: ['Google','Amazon','Facebook'], tags: ['graph','topological-sort','dfs'],
      description: 'Given n courses and prerequisites [a,b] meaning b must be taken before a, determine if you can finish all courses.',
      inputFormat: 'First line: n courses, m prerequisites\nNext m lines: a b', outputFormat: 'true or false',
      constraints: '1 <= n <= 2000',
      sampleTestCases: [{input:'2 1\n1 0',output:'true'},{input:'2 2\n1 0\n0 1',output:'false',explanation:'Cycle exists'}],
      hiddenTestCases: [{input:'3 0\n',output:'true'},{input:'3 2\n1 0\n2 1',output:'true'}],
      hints: ['Build directed graph','Detect cycle using DFS with 3 states: unvisited, visiting, visited'],
      starterCode: { python: 'data = list(map(int, input().split()))\nn, m = data[0], data[1]\nprereqs = [list(map(int, input().split())) for _ in range(m)]\n# Your code here', cpp: '#include <iostream>\n#include <vector>\nusing namespace std;\nint main() {\n    int n,m; cin>>n>>m;\n    vector<pair<int,int>> edges(m);\n    for(auto& e:edges) cin>>e.first>>e.second;\n    // Your code here\n    return 0;\n}', c: '#include <stdio.h>\nint main() {\n    // Your code here\n    return 0;\n}' } },
    { title: 'Clone Graph', difficulty: 'Medium', topic: tids[11], companies: ['Facebook','Amazon','Google'], tags: ['graph','dfs','bfs','hash-table'],
      description: 'Given a reference to a node in a connected undirected graph, return a deep copy (clone) of the graph.',
      inputFormat: 'Adjacency list as n lines: node: neighbor1 neighbor2...', outputFormat: 'Cloned adjacency list (same format)',
      constraints: '0 <= n <= 100',
      sampleTestCases: [{input:'4\n1: 2 4\n2: 1 3\n3: 2 4\n4: 1 3',output:'1: 2 4\n2: 1 3\n3: 2 4\n4: 1 3'}],
      hiddenTestCases: [{input:'0\n',output:''}],
      hints: ['Use DFS with a visited hashmap','Map old node to cloned node to handle cycles'],
      starterCode: { python: '# Your code here', cpp: '#include <iostream>\n#include <unordered_map>\nusing namespace std;\nint main() {\n    // Your code here\n    return 0;\n}', c: '#include <stdio.h>\nint main() {\n    // Your code here\n    return 0;\n}' } },
  ];
}

mongoose.connect(MONGO_URI).then(async () => {
  const db = mongoose.connection.db;
  await db.collection('topics').deleteMany({});
  await db.collection('questions').deleteMany({});

  const topicRes = await db.collection('topics').insertMany(topicDefs);
  const tids = Object.values(topicRes.insertedIds);
  console.log('Topics inserted:', tids.length);

  const questions = buildQuestions(tids);
  await db.collection('questions').insertMany(questions);
  console.log('Questions inserted:', questions.length);

  // Verify
  const topicNames = await db.collection('topics').find({}, {projection:{name:1,order:1}}).sort({order:1}).toArray();
  topicNames.forEach(t => console.log('  -', t.name));

  mongoose.disconnect();
  console.log('DONE');
}).catch(e => { console.error('Error:', e.message); process.exit(1); });
